Fix opencv-python version, last version with python 2.7 support
vlachoudis/bCNC pull request #1454
Opened 2020-09-01 18:46 UTC by sttts

Following https://stackoverflow.com/questions/63346648/python-2-7-installing-opencv-via-pip-virtual-environment.

2020-09-02 08:18 UTC, Harvie commented
Perhaps we can add condition to only apply this version for pyhton 2.

2020-09-02 08:48 UTC, sttts commented
Would rather not try to diverge in versions. It would be a testing nightmare.

2020-09-07 15:12 UTC, sttts commented
@Harvie what do you think? I would add the condition but am not convinced.

2020-09-13 18:03 UTC, GitHubCaps commented
You can do it this way for version dependent. Note that I am using `<=` or `>=` not `==`

```python
#from __future__ import print_function

from setuptools import setup, find_packages

print("Running bCNC setup...")

with open("README.md", "r") as fh:
	long_description = fh.read()

#pip2 install opencv-python==4.2.0.32
from sys import version_info as _version_info

opencv_op = '>=' if _version_info[0] >= 3 else '<='
del _version_info

opencv_version = '4.2.0.32'
opencv_version = 'opencv-python%s%s' % (opencv_op, opencv_version)

#print("opencv_version =",opencv_version)

setup(
	name = "bCNC",
	version = "0.9.14.306",
	license="GPLv2",
	description='Swiss army knife for all your CNC/g-code needs',
	long_description=long_description,
	long_description_content_type="text/markdown",
	packages = find_packages(),
	author = 'Vasilis Vlachoudis',
	author_email='vvlachoudis@gmail.com',
	url="https://github.com/vlachoudis/bCNC",
	include_package_data=True,
	#python_requires="<3.0",
	install_requires = [
		"pyobjc ; sys_platform == 'darwin'",
		"pyobjc-core ; sys_platform == 'darwin'",
		"pyobjc-framework-Quartz ; sys_platform == 'darwin'",

		"pyserial ; sys_platform != 'win32'",  # Windows XP can't handle pyserial newer than 3.0.1 (it can be installed, but does not work)
		"pyserial<=3.0.1 ; sys_platform == 'win32'",
		'numpy>=1.12',
		'Pillow>=4.0',

#		'opencv-python>=2.4 ; ("arm" not in platform_machine) and ("aarch64" not in platform_machine)',  # Note there are no PyPI OpenCV packages for ARM (Raspberry PI, Orange PI, etc...)
		'%s ; ("arm" not in platform_machine) and ("aarch64" not in platform_machine)' % (opencv_version),  # Note there are no PyPI OpenCV packages for ARM (Raspberry PI, Orange PI, etc...)
	],

	entry_points = {
		'console_scripts': [
			#'bCNC = {package}.{module}:{main_function}',
			#'bCNC = bCNC.bCNC:main',
			'bCNC = bCNC.__main__:main',
		]
	},

	classifiers=[
		"Development Status :: 4 - Beta",
		"License :: OSI Approved :: GNU General Public License v2 (GPLv2)",
		"Operating System :: OS Independent",
		"Topic :: Multimedia :: Graphics :: 3D Modeling",
		"Topic :: Multimedia :: Graphics :: Capture",
		"Topic :: Multimedia :: Graphics :: Editors :: Vector-Based",
		"Topic :: Multimedia :: Graphics :: Graphics Conversion",
		"Topic :: Multimedia :: Graphics :: Viewers",
		"Topic :: Scientific/Engineering",
		"Topic :: Scientific/Engineering :: Electronic Design Automation (EDA)",
		"Topic :: Terminals :: Serial",
		"Natural Language :: Dutch",
		"Natural Language :: English",
		"Natural Language :: German",
		"Natural Language :: Spanish",
		"Natural Language :: Portuguese",
		"Natural Language :: Portuguese (Brazilian)",
		"Natural Language :: French",
		"Natural Language :: Italian",
		"Natural Language :: Japanese",
		"Natural Language :: Korean",
		"Natural Language :: Russian",
		"Natural Language :: Chinese (Simplified)",
		"Natural Language :: Chinese (Traditional)",
	]
)
```

2020-09-13 18:39 UTC, GitHubCaps commented
Also, we don't need to `import sys`, we can check for a removed `builtin`

```python
opencv_version = '4.2.0.32'
try:
	# old version
	unicode
except (NameError, AttributeError):
	# newer version
	opencv_op = '>='
else:
	# old version
	opencv_op = '<='
opencv_version = 'opencv-python%s%s' % (opencv_op, opencv_version)
```

2020-09-14 10:48 UTC, sttts commented
I know that conditional requirements are possible. But that's not the point. I think it is wrong to divert for 2.7 and 3.x. Rather bCNC should drop the end-of-life 2.7 and move forward IMO.

2020-11-11 13:56 UTC, bosd requested changes
Please use conditional formatting to keep python2.7 support.

Can you grant me acces to this pull request to commit the code.

2020-11-11 14:01 UTC, Harvie commented
> Can you grant me acces to this pull request to commit the code.

You can fork and make PR yourself...

2020-11-11 16:42 UTC, bosd commented
thanks @Harvie this one can be closed

2020-11-11 16:45 UTC, closed without merging